import React from 'react'
import NavMenu from './navMenu/NavMenu'
import Footer from './footer/Footer'
import Header from './header/Header'

import '../../sass/layout/_layout.scss'


const Layout = ({ children }) => {
    return (
        <div className="container-layout">  
            <Header/>
            <NavMenu />
            <main>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum efficitur mattis libero, quis vehicula purus facilisis in. Donec finibus mauris ornare porttitor lacinia. Vestibulum ut sapien imperdiet, efficitur urna nec, efficitur lorem. Fusce facilisis sem interdum libero interdum blandit. Sed sagittis est a lectus accumsan vestibulum. Praesent at auctor quam, ac pulvinar tellus. Vestibulum non dignissim sem, volutpat sodales dolor. Nullam convallis lobortis neque, non convallis tellus fermentum ut. Nulla eget leo sed urna tincidunt condimentum id sed libero. Praesent nec dignissim metus. Aliquam erat volutpat. In imperdiet eu eros sed hendrerit. Mauris commodo sapien eget diam finibus faucibus.

Vivamus bibendum felis ac est ornare, fringilla ornare sapien consequat. Ut tincidunt diam sit amet purus egestas ullamcorper. Cras non nibh quis libero rutrum condimentum. Nunc suscipit bibendum dui, ut interdum dui dictum hendrerit. Morbi quis elit quis ex finibus tincidunt in consequat enim. Sed sem leo, porta eu diam sit amet, vulputate iaculis nisl. Proin ullamcorper lacinia dictum.

Nulla consectetur felis ut erat faucibus laoreet. Nunc et nulla lacinia, aliquam justo in, pulvinar nisl. Nulla arcu enim, commodo eu felis in, auctor fermentum sapien. Aliquam at odio a dolor elementum condimentum auctor ac augue. Nunc fermentum mi ac viverra pharetra. Sed eget lorem diam. Aenean ultricies quis lorem at volutpat. Mauris quis ante eget ante fermentum consectetur in ac orci. Nulla dictum porttitor turpis sed gravida. Proin sit amet porta ante. Aliquam nisi quam, egestas quis viverra nec, euismod vitae neque. Mauris at hendrerit nisl. Praesent ipsum dolor, scelerisque vel eros sit amet, ornare efficitur erat. Nulla laoreet sem neque, eget scelerisque magna molestie non. Quisque gravida ante vel pulvinar porttitor. In a quam ac lacus tempus tincidunt non a arcu.

Mauris vel ligula arcu. Cras neque nulla, porttitor sit amet volutpat ac, lobortis sit amet sem. Mauris bibendum pretium mi, vel volutpat felis ultrices non. Integer interdum lacinia dictum. Sed sed convallis nibh, at sodales dui. Nam feugiat tortor magna, eu pretium nibh mattis sit amet. Sed elementum molestie pretium. Morbi aliquet urna at augue vestibulum consequat eu cursus nibh. Sed commodo commodo dapibus.

Mauris malesuada sed justo id accumsan. Etiam sit amet laoreet est. Duis quis odio eleifend, aliquam diam a, ornare odio. Quisque id felis quam. Duis arcu felis, viverra eu finibus id, tempus nec nunc. In convallis augue at sodales placerat. Sed quis dui velit. In mattis, ligula sed volutpat cursus, est nibh euismod tellus, a tincidunt turpis justo sit amet elit. Nam pellentesque, diam eu tristique tincidunt, arcu nunc interdum felis, in convallis dolor orci ut massa. Vivamus consequat cursus ipsum, ut finibus mauris maximus eget. Quisque a imperdiet massa. Mauris sed ligula id metus cursus lacinia. Aliquam semper lorem at turpis ultrices, vitae suscipit tortor euismod. In ultrices, dui ac rutrum gravida, lacus erat lobortis arcu, vel blandit arcu nunc porttitor metus.

Morbi semper, justo et facilisis pretium, odio odio pellentesque nisl, nec mollis lorem felis at enim. Donec malesuada viverra lacus ac pulvinar. Maecenas non nibh sit amet diam hendrerit consectetur ac id neque. Fusce sem felis, vestibulum ac lectus egestas, laoreet efficitur turpis. In gravida sodales est quis malesuada. Sed dui elit, tincidunt a tortor non, volutpat feugiat leo. Fusce vel tincidunt magna, at accumsan justo. Phasellus in semper sapien. Nam imperdiet dapibus leo ac rutrum. Vivamus interdum magna finibus, condimentum nibh a, eleifend eros.

Donec consectetur bibendum eros non porttitor. In eget elit sit amet urna sagittis elementum. Integer laoreet consequat quam imperdiet hendrerit. Maecenas non augue id urna placerat congue. Morbi congue sit amet ex nec congue. Quisque vehicula tempus gravida. Vivamus molestie sem quam, id blandit odio lacinia sit amet. Pellentesque ac ante sed justo maximus euismod. Morbi porttitor dictum sem sed porttitor. Curabitur eget pharetra dui. Pellentesque sed sollicitudin metus. Morbi vehicula ultrices dui non viverra. Fusce sed nisi vitae magna placerat ultricies. Suspendisse vitae fermentum risus, in scelerisque magna. Fusce pretium nisi vel consequat eleifend. Phasellus consectetur mattis massa eget vulputate.

Fusce eget sem mi. Maecenas varius nunc tellus, sit amet auctor purus viverra pulvinar. Nunc faucibus gravida tortor, sed pulvinar eros molestie id. Etiam id malesuada sapien, in varius felis. Proin rhoncus viverra ultricies. Phasellus lacinia vulputate ullamcorper. Suspendisse quis rhoncus arcu. Vestibulum ac viverra lacus. Maecenas lobortis, nisi sit amet cursus vehicula, felis est malesuada diam, eget pulvinar libero libero ac lacus. Phasellus porttitor lobortis eros, ut fringilla erat vestibulum at. Vivamus ac congue libero, quis sagittis enim.

Morbi luctus nisi id eros vulputate, id varius velit maximus. Cras eu pretium tellus. Curabitur elementum, quam id congue commodo, velit neque placerat est, ac tempor augue turpis sit amet mauris. Sed venenatis enim mauris, a condimentum metus varius ac. Aenean rutrum sollicitudin lorem non aliquam. In hac habitasse platea dictumst. Sed eget dolor ultrices, finibus velit eget, semper eros. Nullam convallis augue nibh, mattis vestibulum ipsum bibendum non. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Praesent suscipit eleifend posuere. Cras mollis sapien sem, sed tincidunt dolor tempus ac. Nunc est mauris, porttitor id ipsum sit amet, maximus sagittis mauris. Morbi quis orci augue. Donec sit amet consectetur sapien. Phasellus mollis scelerisque mattis. Morbi tincidunt condimentum sem, eget finibus est.

Curabitur neque dolor, viverra efficitur neque eget, hendrerit ornare nisi. Nam at ligula ut urna aliquam molestie vitae eget tortor. Praesent nibh mauris, consequat et fringilla ac, maximus in eros. Donec pellentesque accumsan tincidunt. Pellentesque a sem euismod, ultrices magna at, auctor libero. In tempus tortor augue, vitae congue arcu viverra sed. Donec ultricies sapien quam.

Phasellus non maximus nibh, in venenatis nibh. Donec at imperdiet diam. Integer non risus vulputate tortor egestas condimentum. Integer tincidunt augue semper fringilla eleifend. Nam consequat, felis quis volutpat mollis, augue ipsum tempus dolor, at finibus urna nulla rhoncus felis. Aliquam rhoncus sed dolor vel fringilla. Morbi nec mattis nisl. Aliquam non magna vel odio faucibus ullamcorper. Donec lacus libero, scelerisque ac efficitur fringilla, rutrum feugiat nibh. Fusce vel eros sagittis quam sagittis imperdiet. Duis lacinia sodales ullamcorper. Phasellus eleifend enim ut elit imperdiet laoreet. Vestibulum at varius lectus. Suspendisse tellus elit, porttitor condimentum turpis et, vehicula dapibus nisl. Etiam ut gravida justo.

Nam pharetra venenatis odio, vitae dignissim mauris convallis et. Nullam mi tortor, accumsan et nisl ut, ornare vestibulum enim. Pellentesque iaculis, libero vel bibendum interdum, est erat tincidunt metus, eget semper orci dui ut erat. In pulvinar bibendum libero non mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla tristique tempus lacus, eget venenatis massa mollis a. Etiam ultrices purus nec facilisis aliquet. Nulla luctus dui a nisi ultricies mollis. Aenean placerat nunc eu elit facilisis tempus. Aliquam vehicula egestas nisi, sit amet volutpat sapien gravida sed. Curabitur pretium ut ante at elementum. Phasellus fringilla, nunc sed tincidunt ullamcorper, nisi dui sodales elit, sit amet imperdiet justo elit eu diam.

Donec id nibh quis orci sagittis ullamcorper eget eu erat. Quisque ac mauris id felis accumsan molestie. Praesent tempor lectus nec leo sagittis, sed molestie quam tristique. Duis ut ligula nibh. Proin faucibus orci eros, vitae aliquam nisl lacinia at. Ut elementum nisi nisi, eget tincidunt sapien cursus at. Vestibulum et ultricies augue, vel egestas purus. Sed ut lorem feugiat, porta nisi id, vulputate sapien. Duis laoreet ante et molestie malesuada. Fusce congue dignissim odio, sit amet placerat risus volutpat ut. Ut bibendum libero id justo pharetra, non blandit sem aliquet. Fusce ipsum ante, aliquet ac leo vel, eleifend condimentum eros. Vivamus non pulvinar leo, eu porta leo. Etiam eleifend augue vitae metus varius, a ullamcorper est iaculis. In a rhoncus arcu. Aenean volutpat orci varius, viverra ex eu, hendrerit magna.

Pellentesque nunc ligula, rhoncus eget nulla at, blandit ullamcorper lectus. Sed consequat nibh at vestibulum scelerisque. Nam finibus lacinia sem sed elementum. Duis viverra nisi accumsan sagittis pulvinar. Sed sit amet ante lobortis, finibus magna vitae, iaculis est. Nunc vel turpis ac augue volutpat gravida. Vestibulum vulputate cursus turpis sit amet finibus. Sed orci nisl, sollicitudin at mauris id, convallis accumsan justo. Mauris fringilla blandit augue, vel bibendum dolor auctor et. In venenatis consequat ipsum, quis dignissim leo. Vivamus mollis sem ut felis eleifend vehicula at non enim. Sed at congue libero, nec lobortis ante. Nunc elit ante, vehicula vel tincidunt a, egestas ac elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut eu vehicula augue. Suspendisse nec nulla rhoncus, finibus dui sed, pellentesque mauris.

Sed ac ipsum sit amet massa egestas mattis. Sed dictum ac nisl sed egestas. Aenean quis odio massa. Suspendisse gravida libero in consectetur laoreet. Aenean lectus sapien, auctor in semper non, vulputate eu ex. Praesent in mauris lacus. Morbi diam risus, fringilla sit amet sodales id, suscipit pharetra metus. Integer id euismod sem. Cras quis eros eget purus gravida molestie quis at sapien. Proin consectetur accumsan est nec accumsan. Donec ut sapien et diam tristique hendrerit. Pellentesque nec lectus ullamcorper, scelerisque lorem tincidunt, ultricies dui.

Fusce rutrum varius tortor, id suscipit nibh ultrices vitae. Donec ac quam molestie, hendrerit libero vel, eleifend tortor. Nulla sed tortor semper, semper magna non, luctus elit. Ut accumsan purus at molestie venenatis. Proin bibendum ligula tellus, eu scelerisque sem lobortis eget. Morbi consequat tincidunt ultricies. Vestibulum venenatis ante vel velit faucibus rhoncus. Curabitur aliquet lectus ante, ac ultrices ante ornare in. Duis eu suscipit felis, non pulvinar massa. Duis a augue nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis pretium interdum sem id pretium. Integer tincidunt gravida ornare. Vivamus urna quam, faucibus eget tempus vitae, euismod laoreet lorem. Proin maximus eros leo, non tristique erat ullamcorper nec.

Nam tristique nibh vel mi tempor, quis efficitur elit blandit. Nunc commodo porttitor erat id venenatis. Donec vehicula nulla id tincidunt faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus maximus tortor eu diam maximus, sit amet varius justo maximus. Suspendisse id dignissim sem. Sed nisi nisl, tempus tempus nisl eu, ultrices ornare enim. Cras consectetur risus vel gravida elementum. Praesent sagittis, mauris nec ullamcorper venenatis, arcu ex vehicula augue, vitae aliquet nisi dolor nec elit. Vestibulum rhoncus sodales lorem vitae tempor. Integer eget ligula urna.

Donec vitae lectus egestas, dignissim velit eget, rutrum ipsum. Curabitur at ultricies lorem, quis congue odio. Phasellus porta ullamcorper dolor, et tristique orci porta eu. Pellentesque luctus odio eu enim aliquet, id aliquam sem suscipit. Cras facilisis condimentum enim, ut tincidunt arcu sagittis eget. Ut sem turpis, tempus eu commodo ac, vehicula sit amet ligula. Integer tempus placerat tellus eu ultricies. In vulputate ligula dictum nunc ullamcorper, sit amet aliquam orci accumsan. Vestibulum sit amet consectetur erat, ut porta diam.

Nam dolor orci, volutpat at facilisis in, ultricies quis erat. Pellentesque scelerisque accumsan dictum. Aenean ac nibh rhoncus, lacinia velit eget, eleifend turpis. Suspendisse in facilisis justo, et aliquam ipsum. In quis erat aliquam, hendrerit odio ac, fringilla sem. Sed lectus neque, hendrerit in laoreet nec, fermentum nec ex. Vestibulum eu scelerisque orci. Maecenas sodales ligula et nisi euismod pulvinar. Phasellus vehicula, lacus vitae maximus bibendum, risus nisi porttitor orci, non convallis ex nisl nec ex. Curabitur pulvinar ut libero ut convallis. Nunc quis felis mattis tellus dignissim tristique ut a dolor. Nullam tristique, quam id aliquam tincidunt, neque felis aliquam enim, in gravida nulla sapien in ex. Aliquam laoreet metus ac vestibulum tincidunt. Sed vulputate rhoncus ante, eu ornare urna pellentesque non. Aliquam in mollis velit, nec pellentesque risus.

Nunc nec orci neque. Sed commodo lobortis magna, sed ullamcorper turpis sagittis non. Phasellus consequat porttitor quam, id faucibus nisl sollicitudin sed. Sed laoreet purus dolor, sit amet faucibus quam venenatis vitae. Suspendisse vulputate maximus vehicula. Duis a nunc non tortor fermentum faucibus. Nam fringilla placerat orci, in ornare erat ultricies sit amet. Sed ac dignissim nibh, et euismod tortor.

Phasellus faucibus arcu diam, quis vulputate lectus consectetur vel. Vivamus nunc eros, vehicula quis sodales a, accumsan eu sapien. Phasellus id aliquet ligula. Maecenas ac nunc purus. Aliquam fermentum urna vitae nisl volutpat volutpat. Quisque porttitor laoreet pulvinar. Nunc sit amet nunc eu nulla ultricies luctus hendrerit eu nibh.

Etiam quis quam vitae elit pellentesque tempor. Ut dictum arcu in sapien vestibulum posuere. Nunc semper porta magna a commodo. Nunc at augue id dolor maximus vestibulum a ac enim. Quisque nec purus odio. Donec porttitor, mauris non elementum congue, turpis mi pharetra est, a tincidunt nibh nulla eget ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi et tempor magna. Fusce pretium rutrum nisi, nec egestas mi eleifend eget. Sed vehicula odio et urna aliquam venenatis. Duis pretium turpis placerat sagittis blandit. Nunc fringilla lorem ac justo pellentesque tempus. Cras condimentum tortor ac lacus semper, eget mattis justo convallis. Sed sed leo nec odio fringilla porttitor.

Nunc mattis mattis ex at varius. Phasellus fermentum a tellus a auctor. Nunc nec malesuada ligula. Integer ac semper ex. Curabitur tristique nisi quis elit ornare, in auctor nisi suscipit. Etiam at maximus lacus. In hac habitasse platea dictumst. Curabitur vitae feugiat eros, sit amet sodales tortor. Proin id libero mauris. Donec ut dictum nisi. Praesent ante dolor, ultricies vitae ipsum vel, tempus varius urna. Praesent ultricies, ipsum quis volutpat vulputate, sem sem tincidunt odio, nec vehicula purus lorem eget ligula. Nulla facilisi. In cursus, orci sed placerat tempus, libero nibh euismod tortor, id cursus est ipsum eu lorem. Vivamus sit amet neque sit amet purus viverra elementum quis sed urna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Fusce in lorem eu lacus gravida tincidunt non ac mi. In semper semper fringilla. Duis cursus lorem in metus finibus, id dapibus erat bibendum. Nam in congue mi. Vestibulum blandit non neque id porta. Nullam quis lacinia nunc. Cras eleifend ullamcorper porttitor. Donec bibendum auctor justo, sit amet commodo justo sodales non. Aenean sagittis ac mauris eu fermentum. Sed elementum egestas tellus, sit amet suscipit quam condimentum viverra.

Mauris a hendrerit dolor, sed gravida nisi. Phasellus et ligula leo. Praesent a nisi a lectus tempus bibendum in sed urna. Aenean aliquam sed sem sit amet pharetra. Nunc lectus nisi, tempus vel consectetur nec, scelerisque sed tellus. Cras posuere orci et imperdiet interdum. Praesent malesuada erat eget orci maximus gravida. Nunc fringilla ullamcorper turpis sit amet aliquam. Pellentesque vulputate augue eget mi dignissim, in ultrices purus molestie. Nullam neque mi, porttitor et commodo ultrices, consectetur eu odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed justo lectus, mattis a enim id, ultricies lacinia augue. Curabitur imperdiet interdum dui, ut bibendum tellus molestie et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus rhoncus metus vitae felis imperdiet facilisis.

Morbi nec turpis nec tortor consequat gravida eget quis odio. Proin maximus, est quis scelerisque sagittis, mauris massa aliquet libero, et molestie lectus tortor non tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam non malesuada odio, sed lacinia justo. Nulla facilisi. Duis scelerisque elementum est, quis feugiat elit condimentum a. In accumsan lacus vitae est tempus pulvinar. Nulla facilisi. Quisque porta sodales metus at cursus. Fusce quis scelerisque elit. Sed mattis enim at erat commodo, et rutrum sapien congue. Vestibulum tempor erat eget tristique vehicula. Aliquam odio mauris, convallis ac eros quis, pulvinar ullamcorper nulla. Duis mollis posuere neque eu laoreet.

Etiam vitae urna id augue dictum fermentum. Vivamus egestas eros vel condimentum lacinia. Mauris id suscipit mauris, sed bibendum nibh. In vestibulum ornare tellus at molestie. Mauris lobortis ex a accumsan semper. Morbi euismod, lectus vel ultrices venenatis, arcu nunc bibendum elit, eget ultrices leo turpis vitae sem. Duis eros quam, imperdiet ullamcorper eleifend non, ullamcorper sit amet urna. Praesent pharetra malesuada justo, vulputate posuere dolor tristique sed. Nunc maximus turpis at sem suscipit, mollis molestie dolor bibendum. Donec tristique tellus mauris, id dapibus lacus mattis non. Duis iaculis elementum scelerisque.

Praesent a purus finibus, semper nulla eget, faucibus lorem. Duis quis eros egestas, scelerisque nisl vitae, pharetra odio. Morbi ligula libero, tempus vitae egestas et, ornare scelerisque neque. Duis id ipsum at sapien aliquet ultricies sit amet sed magna. Sed a orci in dui condimentum condimentum. Praesent ex nunc, feugiat nec nisl eget, condimentum accumsan arcu. Aenean consequat, nunc a vulputate ultrices, risus nisl consectetur diam, id commodo risus sapien vitae eros.

In hac habitasse platea dictumst. Pellentesque sem massa, malesuada non sem id, elementum interdum lacus. Suspendisse potenti. Etiam consequat, odio a fringilla rhoncus, sem eros interdum urna, sed venenatis justo odio ut mi. Proin id pretium mi, sed placerat urna. Proin auctor aliquam arcu, ut blandit justo maximus sed. Maecenas gravida leo at arcu fringilla, venenatis placerat ante blandit. Maecenas sagittis urna ac dignissim feugiat. Nunc bibendum justo sed tortor hendrerit pharetra. Phasellus aliquam quam velit, scelerisque bibendum est sagittis eu. Aenean rhoncus in ligula nec cursus.

Generados 30 párrafos, 2788 palabras, 18798 bytes de Lorem Ipsum</main>
            <Footer />
        </div>
    )
}

export default Layout;